### ISSUE TITLE
No sabemos cómo llamar a cada una de las palabras clave

### ISSUE THREAD

**Issue by moshidev** [JaimeGM96/RutasAutobuses#10]
Es necesario establecer cómo se va a llamar a cada uno de los conceptos. Desconocemos todavía todos los conceptos del dominio.

**Comment by moshidev** [comment]
¿Cómo ves estos términos y sus definiciones? ¿Se te ocurre alguno más?

* **Línea.** Viene representada por un número. Representa un autobús que visita consecución de paradas no repetidas.
* **Parada.** Viene representada por un número. Tiene una ubicación geográfica. Distintas líneas pueden compartir una única parada.
* **Recorrido.** Camino que conecta una parada con otra.
* **Consulta.** Deseo de conocer un recorrido que conecte una parada de origen con otra de destino a una hora determinada.

**Comment by JaimeGM96** [comment]
¿La consulta seria el equivalente a ruta? Creo que es más representativo que se llame ruta. ¿Y el recorrido seria solo entre paradas? ¿Sería la heurística que tendríamos que aplicar para conocer cuál es la ruta más optima? Especificaría que la consulta/ruta sería el conjunto de recorridos que conectan una parada origen con una destino.

**Comment by moshidev** [comment]
una parada y línea de origen, cero o más paradas y líneas en las que hacer transbordo y una parada y línea de destino

**Comment by moshidev** [comment]
> ¿La consulta seria el equivalente a ruta?

https://github.com/JaimeGM96/RutasAutobuses/issues/16#issuecomment-1772183840

> Creo que es más representativo que se llame ruta.

Sí, consultando la definición de ruta también entiendo que utilizar *ruta* (*itinerario para el viaje* según la segunda acepción) es más claro que utilizar *recorrido*.

> ¿Y el recorrido seria solo entre paradas?

No, estaba concebido como la nueva definición que he dado para *ruta*.

> ¿Sería la heurística que tendríamos que aplicar para conocer cuál es la ruta más optima?

Creo que no, no? En plan, la heurística es el que tenga el tiempo estimado según el horario más corto.

> Especificaría que la consulta/ruta sería el conjunto de recorridos que conectan una parada origen con una destino.

Hecho, más o menos.

¿Cómo lo ves así?

* **Línea**. Viene representada por un número. Representa un autobús que visita consecución de paradas no repetidas.
* **Parada**. Viene representada por un número. Tiene una ubicación geográfica. Distintas líneas pueden compartir una única parada.
* **_Ruta_**. Camino que conecta una parada con otra. _Una parada y línea de origen a una hroa, cero o más paradas y líneas en las que hacer transbordo a una hora y una parada y línea de destino a una hora_.
* **Consulta**. Deseo de conocer _una ruta_ que conecte una parada de origen con otra de destino a una hora determinada. _Entendido como acción de consultar cuál es la ruta óptima_.

**Comment by JaimeGM96** [comment]
Mejor que antes, lo voy muy bien!
