### ISSUE TITLE
No sabemos si existe conexión entre dos paradas

### ISSUE THREAD

**Issue by moshidev** [JaimeGM96/RutasAutobuses#11]
Relacionado con #3, #4.

Ya sea directa o mediante transbordos.

**Comment by moshidev** [comment]
Relacionado con #10.

Existe conexión entre dos paradas si:
* Existe una línea la cual pase por la parada de origen y posteriormente por la de destino.
* Existe una línea la cual pase por la parada de origen y posteriormente por una la cual tenga otra línea que pase por la de destino.
* Igual que la condición anterior solo con hasta n niveles de recursividad.

**Comment by moshidev** [comment]
Tal vez se podría saber a través de un objeto que nos devolviese el conjunto de rutas posibles entre dos paradas. Échale un vistazo al último commit a ver qué te parece.

**Comment by JaimeGM96** [comment]
¿El transbordo no tendría que tener un vector de líneas? Es decir, se necesitaría saber con cuantas líneas y cuales son las que coinciden en una misma parada donde se podrá hacer transbordo, ¿no?

**Comment by moshidev** [comment]
La estructura que representa un transbordo tal vez no tiene el mejor nombre... La había concebido como acción de transbordar, y la estructura representa ese evento.

O sea, una ruta está compuesta por distintos transbordos. Cojo el primer autobús: primer transbordo. Me bajo del primero: segundo transbordo. Me subo al segundo: tercer transbordo. Me bajo del segundo, he llegado a mi destino: cuarto transbordo.

Luego,
>  se necesitaría saber con cuantas líneas y cuales son las que coinciden en una misma parada donde se podrá hacer transbordo

esta info se puede recuperar de estas dos variables de instancia:

```
struct BuscadorRutas {
	lineas: Map<NumLinea, Linea>,
	paradas: Map<NumParada, Vec<NumLinea>>,
}
```

**Comment by JaimeGM96** [comment]
Vale, me ha quedado más claro.
