### ISSUE TITLE
¿Qué es una consulta?

### ISSUE THREAD

**Issue by moshidev** [JaimeGM96/RutasAutobuses#16]
Relacionado con #10.

Entendemos que:
* Establece una parada de origen y una parada de destino.
* Se realiza en una fecha concreta, a una hora concreta.
* Se quiere que devuelva una parada y línea de origen, cero o más paradas y líneas en las que hacer transbordo y una parada y línea de destino. Es decir, se quiere que devuelva un recorrido.

Una consulta devuelve un recorrido si existe conexión (#11) entre el origen y el destino. Si no, tiene que indicar este hecho.

**Comment by JaimeGM96** [comment]
Como he comentado en #10, ¿La consulta sería el equivalente a ruta? Y en cuanto al recorrido, ¿sería la representación de un camino entre dos paradas? La ruta podría ser el conjunto de recorridos.

**Comment by moshidev** [comment]
Se refiere a la acción de consultar.
Está pensado como una interfaz que ofrezca el servicio de:
> Consulto cómo llegar a un destino desde un origen a esta hora en concreto. ¿qué autobús/combinación de autobuses tendría que coger? (de forma que sea óptimo según el tiempo, indique transbordos, etc)
