### ISSUE TITLE
Elección de lenguaje de programación

### ISSUE THREAD

**Issue by moshidev** [JaimeGM96/RutasAutobuses#5]
Yosh! Me toca trabajar sobre tu repositorio para el objetivo 2.

Leyendo tu documentación me da la impresión de que cualquier lenguaje de programación de propósito general sería una buena elección, ¿cómo lo ves? Se me ocurren, por decir, que se podría utilizar Rust o Go por ejemplo.

El compilador de Rust ayuda a mucho a escribir código correcto y eficiente computacionalmente, aun cuando es concurrente. Además, cargo permite compilar y crear paquetes, librerías, etc con comandos súper fáciles (casi que es más fácil que ejecutar código javascript).

Go por otra parte, por lo que he escuchado (que no ha sido mucho), es un buen lenguaje de programación para todo lo que se va a desplegar en la nube. Tiene herramientas para networking, infraestructura, concurrecia, etc.

**Comment by JaimeGM96** [comment]
Hola! Pues si lo ves bien, podemos hacer el proyecto en Rust, por lo que he visto me ha gustado y me gustaría conocerlo más en profundidad. Coméntame que te parece!
