### ISSUE TITLE
No sabemos qué rutas de autobuses existen en Granada

### ISSUE THREAD

**Issue by moshidev** [JaimeGM96/RutasAutobuses#7]
Relacionado con #3, #4.

No sabemos las paradas ni el horario de cada ruta. No sabemos la frecuencia de actualización, si se van actualizando a lo largo del día o se mantienen iguales a lo largo del tiempo.

**Comment by moshidev** [comment]
@JaimeGM96 échale un vistazo a esto porfa

**Comment by JaimeGM96** [comment]
Las rutas tienes unos horarios fijos. Depende de la hora a la que consultes las posibles rutas es posible que se calculen diferentes rutas optimas ya que el tiempo de llegada de un autobús puede ser demasiado grande con respecto a otro, teniendo en cuenta los transbordos, etc.

**Comment by moshidev** [comment]
Para cada línea, cada parada tiene un horario o sólo hay un horario de salida?
